version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lkbhos
      MONGO_INITDB_ROOT_PASSWORD: lkbh11234
    volumes:
      - ./mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 15s
      retries: 10

  api:
    build: ./server/
    container_name: api
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: mongodb://lkbhos:lkbh11234@mongodb:27017/lkbhosdb
    volumes:
      - ./server/files:/app/files:rw
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
