version: '3.8'

services:
  # mongodb:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: mongodb_replica
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - ./mongodb-keyfile:/mongodb-keyfile
  #   command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/mongodb-keyfile/mongodb-keyfile", "--auth"]
  #   networks:
  #     - app_network

  # go_api:
  #   build:
  #     context: ./Go_api
  #     dockerfile: Dockerfile
  #   container_name: go_api
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - MONGODB_URI=mongodb://admin:password@mongodb:27017/admin?replicaSet=rs0&authSource=admin
  #   volumes:
  #   - ./files:/app/files
  #   - ./convert:/app/convert
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app_network

  nextjs:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    ports:
      - "3000:3000"  
    working_dir: /app
    # depends_on:
    #   - go_api
    networks:
      - app_network
    

# volumes:
#   mongodb_data:
#     driver: local

networks:
  app_network:
    driver: bridge